#========================默认环境配置======================
#Spring Boot应用的配置文件；yml 格式
Srping:
  profiles:
    #active: dev #激活指定配置文件

#控制台打印自动配置报告==，这样我们就可以很方便的知道哪些自动配置类生效；
#debug: true


#端口配置
#server:
  #port: 8080
  #context-path: /blog #项目访问路径








#可通过多配置多文件形式不同环境不同配置，或一个文件里面通过‘---’分开每个环境配置 spring.profiles 来指定环境
---

#========================测试环境配置======================
#Spring Boot应用的配置文件；yml 格式

spring:
  profiles: dev

#端口配置
server:
  port: 8081



---
#========================生产环境配置======================
#Spring Boot应用的配置文件；yml 格式

spring:
  profiles: prod

#端口配置
server:
  port: 9090