#通过@ConfigurationProperties 注解，可以直接映射到bean中 支持复杂数据配置
mainConfig:
  name: "lhj"
  #obj:
    #name: "aa"
    #age: 23
  obj: { id："1",name: "asf" }
  #array:
      #- lisi
      #- zhaoliu
  array: ["hah","哈哈"]
  array2: [{a: "aa",b: "bb"}]
