-- 管理列表按钮
-- 查询表单操作按钮
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000000', '${appid!'BASIC'}', '${menuid}', '查询', '', '/${app}/${depname}/find', 'icon-search4', 1, '查询表单操作按钮', '${deps}', 'handel:function(){\n ${depname}.reload${depName}();\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000001', '${appid!'BASIC'}', '${menuid}', '清空', '', '', 'icon-reset', 2, '查询表单操作按钮', '/form/form', 'handel:function(){\n     new Form(\"form[name=查询${name}表单]\").clear();\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000002', '${appid!'BASIC'}', '${menuid}', '新增', '', '/${app}/${depname}/add;/${app}/${depname}/update', 'icon-add', 3, '查询表单操作按钮', '${deps}', 'handel:function(){\n   ${depname}.navbar.forward({\n      title:\'新增${name}\',\n      url:JHtml.context+\'/${app}/${depname}/add?menuid=${addmenuid}\'\n  });\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');

-- 查询结果操作列表按钮
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000003', '${appid!'BASIC'}', '${menuid}', '编辑', '列表-编辑', '/${app}/${depname}/update', 'icon-pencil5', 1, '查询结果列表操作按钮', '${deps}', 'handel:function(index,row){\n   ${depname}.navbar.forward({\n     title:\'编辑${name}信息\',\n     url:JHtml.context+\'/${app}/${depname}/update?menuid=${updatemenuid}&sid=\'+row.sid\n   });\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking',NULL, '');
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000004', '${appid!'BASIC'}', '${menuid}', '详情', '列表-详情', '/${app}/${depname}/detail', 'icon-magazine', 2, '查询结果列表操作按钮', '${deps}', ' handel:function(index,row){\n  ${depname}.navbar.forward({\n     title:\'${name}详情信息\',\n     url:JHtml.context+\'/${app}/${depname}/detail?sid=\'+row.sid+\'&menuid=${detailmenuid}\'\n  });\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000005', '${appid!'BASIC'}', '${menuid}', '删除', '列表-删除', '/${app}/${depname}/deletes', 'icon-subtract', 3, '查询结果列表操作按钮', '${deps}', 'handel:function(index,row){\n  ${depname}.delete${depName}({sid:row.sid,orgId:row.orgId});\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');

-- 新增页面操作按钮
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000006', '${appid!'BASIC'}', '${addmenuid}', '保存', '', '/${app}/${depname}/add', 'icon-floppy-disk', 1, '表单操作按钮', '/script/${app}/${depname}', 'handel:function(){\n  ${depname}.save${depName}();\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000007', '${appid!'BASIC'}', '${addmenuid}', '返回', '', '', 'icon-reply', 2, '表单操作按钮', '/script/${app}/${depname}', 'handel:function(){\n   ${depname}.navbar.back();\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');


-- 修改页面操作按钮
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000008', '${appid!'BASIC'}', '${updatemenuid}', '保存', '', '/${app}/${depname}/update', 'icon-floppy-disk', 1, '表单操作按钮', '/script/${app}/${depname}', 'handel:function(){\n  ${depname}.save${depName}();\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}00000009', '${appid!'BASIC'}', '${updatemenuid}', '返回', '', '', 'icon-reply', 2, '表单操作按钮', '/script/${app}/${depname}', 'handel:function(){\n   ${depname}.navbar.back();\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');


-- 详情页面操作按钮
INSERT INTO `unib_buttons` (`SID`, `APP_ID`, `MENU_ID`, `NAME`, `ALIAS`, `ACT_URL`, `ICONS`, `ORDERED`, `POSITION`, `DEPS`, `EVENTES`, `STATUS`, `SIGN`, `CREATED`, `CREATED_BY`, `LAST_UPDATED`, `LAST_UPDATED_BY`) VALUES ('1000${.now?string("yyyyMMddHHmmss")}${seed}000000010', '${appid!'BASIC'}', '${detailmenuid}', '返回', '', '', 'icon-reply', 2, '表单操作按钮', '/script/${app}/${depname}', 'handel:function(){\n   ${depname}.navbar.back();\n}', 1, '1', '${.now?string("yyyy-MM-dd HH:mm:ss")}', 'jeking', NULL, '');
